### ISSUE TITLE
Problems encountered during run the autovec.py

### ISSUE THREAD

**Issue by A1icezz** [ucb-bar/NeuroVectorizer#12]
Hello, I encountered some problems while running the autovec.py, I hope I can get your help!
First, when I run the autovec.py, I got errors as follows:
```
Traceback (most recent call last):
  File "autovec.py", line 33, in <module>
    from envs.neurovec import NeuroVectorizerEnv
  File "/home/milet/neuro-vectorizer-master/envs/neurovec.py", line 47, in <module>
    from utility import get_bruteforce_runtimes, get_O3_runtimes, get_snapshot_from_code, get_runtime, get_vectorized_codes, init_runtimes_dict, get_encodings_from_local, MAX_LEAF_NODES, pragma_line
  File "/home/milet/neuro-vectorizer-master/utility.py", line 43, in <module>
    MAX_LEAF_NODES = os.environ['MAX_LEAF_NODES']
  File "/home/milet/anaconda3/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAX_LEAF_NODES'
```

I checked the system's environ keys and found there are no 'MAX_LEAF_NODES'in my system, so in order to solve the problem, I change the code in utility.py.
```
before:
MAX_LEAF_NODES = os.environ['MAX_LEAF_NODES']
TEST_SHELL_COMMAND_TIMEOUT = os.environ['TEST_SHELL_COMMAND_TIMEOUT']
after:
MAX_LEAF_NODES = 100
TEST_SHELL_COMMAND_TIMEOUT = 10
```

Unfortunately, I encountered a new problem, I could get the meaning of the error, so I hope someone can help me. Thank you!
```
Traceback (most recent call last):
  File "autovec.py", line 59, in <module>
    loggers=[TBXLogger]
  File "/home/milet/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 342, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_autovec_00000])
(pid=6111) 2021-05-15 15:50:25,693	WARNING deprecation.py:30 -- DeprecationWarning: `sample_batch_size` has been deprecated. Use `rollout_fragment_length` instead. This will raise an error in the future!
(pid=6111) 2021-05-15 15:50:25,693	INFO trainer.py:585 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=6111) cp: cannot stat './training_data/*': No such file or directory
(pid=6111) creating ./new_garbage_6111 directory
(pid=6111) running: cp -r ./training_data/* ./new_garbage_6111
```

**Comment by AmeerHajAli** [comment]
Did you follow the instructions?
```
- cd preprocess
- source ./configure.sh //you might need here to modify SOURCE_DIR to point to your train data.
- source ./preprocess.sh //this will generate the bag of words embedding of the AST trees for the training data (the training set is in "training_data" feel free to add more samples).
- python autovec.py
```

When you source ./configure.sh it sets the MAX_LEAF_NODES.
